config/routes.rb
Rails.application.routes.draw do
 
  #get 'notifications/index'

 resources :projecttasks
  
  resources :customers
  
  resources :projects do
   resources :projecttasks
   resources :memberships
   member do
    get :membering;
    get :member_list;
   end
  end
  
  namespace :taskline do
    resources :task_comments
  end
  resources :tasks

resources :qacomments
  resources :qas do
   resources :qacomments
  end
  
  resources :comments
  get 'users/index'
  get 'users/show'

  devise_for :users, controllers: { 
   sessions: "users/sessions", 
   registrations: "users/registrations", 
   passwords: "users/passwords",
   omniauth_callbacks: "users/omniauth_callbacks" 
  }
  
  resources :users, only:[:index, :show, :update] do
   resources :tasks
   resources :notifications, only: [:index]
   member do
    get :following, :followers;    
   end
   
   resources :submit_requests , shallow: true do
    get 'approve'
    get 'unapprove'
    get 'reject'
     collection do
      get 'inbox'
     end
    end
   end
  
  namespace :taskline do
   resources :tasks do
   resources :task_comment
   post "ungoodjob"
   post "goodjob"
  end
 end
 

  resources :relationships, only:[:create, :destroy]
  
  root to: "top#index"
  get 'contact/index'
  get 'contact/new'
  post 'contact/confirm'
  post 'contact/thanks'
  
  resources :blogs do
    resources :comments
  end
  
  resources :conversations do
   resources :messages
  end
  

  

end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :user
  belongs_to :project

end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action :set_membership, only: [:show, :edit, :update]
  before_action :authenticate_user!
  respond_to :html, :js

  # GET /memberships
  # GET /memberships.json
  def index
    #@memberships = Membership.all
    @memberships = Membership.page(params[:page])
  end

  # GET /memberships/1
  # GET /memberships/1.json
  def show

  end

  # GET /memberships/new
  def new
    @membership = Membership.new
  end

  # GET /memberships/1/edit
  def edit
  end

  # POST /memberships
  # POST /memberships.json
  def create
    @membership = Membership.new(membership_params)
    @user = User.find(params[:membership][:user_id])
    #binding pry
    @pjnum =  params[:membership][:project_id]
    
     #binding pry
    
    #@h2 = Hash.new
    #@h2= { first: 1, second: 2}
    
   #binding pry
    respond_to do |format|
      if @membership.save
        #format.html { redirect_to membering_project_path(@membership.project_id) , notice: 'メンバーに追加しました' }
        format.js  #{ redirect_to membering_project_path(@membership.project_id)  }
       # format.json { render :show, status: :created, location: @membership }
      else
        format.html { render :new }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memberships/1
  # PATCH/PUT /memberships/1.json
  # def update
  #   respond_to do |format|
  #     if @membership.update(membership_params)
  #       format.html { redirect_to @membership, notice: '更新しました' }
  #       format.json { render :show, status: :ok, location: @membership }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @membership.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /memberships/1
  # DELETE /memberships/1.json
  def destroy
     @pj_num = params[:membership]
     #binding.pry
    @membership= Membership.find_by(user_id: @pj_num[:user_id])
    @user = User.find(params[:membership][:user_id])
    @membership.destroy
    respond_to do |format|
      #format.html { redirect_to  membering_project_path(@membership.project_id) , notice: 'メンバーから削除しました' }
      #format.json { head :no_content }
      format.js
    end
  end
  
  


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_membership
      @membership = Membership.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def membership_params
      params.require(:membership).permit(:user_id, :project_id)
    end
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/views/memberships/_form.html.erb
<%= form_for(@membership) do |f| %>
  <% if @membership.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@membership.errors.count, "error") %> prohibited this membership from being saved:</h2>

      <ul>
      <% @membership.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :project_id %><br>
    <%= f.text_field :project_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/memberships/create.js.erb
$("#add_del_form_"+"<%= @user.id %>").html('<%= escape_javascript(render partial:'projects/dele_form',locals:{user: @user , pj_num: @pjnum} ) %>')

app/views/memberships/destroy.js.erb
$("#add_del_form_"+"<%= @user.id %>").html('<%= escape_javascript(render partial:'projects/add_form',locals:{user: @user , pj_num: @pjnum} ) %>')

app/views/memberships/edit.html.erb
<h1>Editing Membership</h1>

<%= render 'form' %>

<%= link_to 'Show', @membership %> |
<%= link_to 'Back', memberships_path %>

app/views/memberships/index.html.erb
<p id="notice"><%= notice %></p>

<h4>新規顧客登録</h4>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>User</th>
      <th>Project</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @memberships.each do |membership| %>
      <tr>
        <td><%= membership.user.name %></td>
        <td><%= membership.project.title%></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Membership',  new_project_membership_path %>

app/views/memberships/new.html.erb
<h1>New Membership</h1>

<%= render 'form' %>

<%= link_to 'Back', memberships_path %>

app/views/memberships/show.html.erb
<p id="notice"><%= notice %></p>

<div>
  <strong>顧客:</strong>
  <%= @membership.user %>
</div>

<div>
  <strong>Project:</strong>
  <%= @membership.project %>
</div>

<%= link_to 'Edit', edit_membership_path(@membership) %> |
<%= link_to 'Back', memberships_path %>