config/routes.rb
Rails.application.routes.draw do
 
  #get 'notifications/index'

 resources :projecttasks
  
  resources :customers
  
  resources :projects do
   resources :projecttasks
   resources :memberships
   member do
    get :membering;
    get :member_list;
   end
  end
  
  namespace :taskline do
    resources :task_comments
  end
  resources :tasks

resources :qacomments
  resources :qas do
   resources :qacomments
  end
  
  resources :comments
  get 'users/index'
  get 'users/show'

  devise_for :users, controllers: { 
   sessions: "users/sessions", 
   registrations: "users/registrations", 
   passwords: "users/passwords",
   omniauth_callbacks: "users/omniauth_callbacks" 
  }
  
  resources :users, only:[:index, :show, :update] do
   resources :tasks
   resources :notifications, only: [:index]
   member do
    get :following, :followers;    
   end
   
   resources :submit_requests , shallow: true do
    get 'approve'
    get 'unapprove'
    get 'reject'
     collection do
      get 'inbox'
     end
    end
   end
  
  namespace :taskline do
   resources :tasks do
   resources :task_comment
   post "ungoodjob"
   post "goodjob"
  end
 end
 

  resources :relationships, only:[:create, :destroy]
  
  root to: "top#index"
  get 'contact/index'
  get 'contact/new'
  post 'contact/confirm'
  post 'contact/thanks'
  
  resources :blogs do
    resources :comments
  end
  
  resources :conversations do
   resources :messages
  end
  

  

end

app/models/submit_request.rb
class SubmitRequest < ActiveRecord::Base
  belongs_to :task
  belongs_to :user
  belongs_to :charger, class_name: 'User', foreign_key: 'charge_id'
  
  has_many :notifications, dependent: :destroy
  has_many :conversations, through: :notifications, source: :submit_request_id
  #has_many :conversations, through: :notifications, source: :comment
  
  accepts_nested_attributes_for :notifications
  
  #scope :select_submit_request, -> {find(params[:id]) }
  scope :select_submit_request, ->(s_id) { find(s_id) }

end

app/controllers/submit_requests_controller.rb
class SubmitRequestsController < ApplicationController
  before_action :set_submit_request, only: [:show, :edit, :update, :destroy ]
  before_action :set_submit_request02, only: [:approve, :unapprove, :reject]
  before_action :authenticate_user!
  after_action :sending_pusher02, only: [:create]
  
  def index
    #自分が依頼したものが表示される
    @submit_requests = SubmitRequest.where(user_id: current_user.id).order(updated_at: :desc)
  end

  def new
    #つながっているユーザー
    friendsQuery = "select * FROM (SELECT users.* FROM users INNER JOIN relationships ON users.id = relationships.followed_id WHERE relationships.follower_id = " + current_user[:id].to_s + ") X INNER JOIN (SELECT users.* FROM users INNER JOIN relationships ON users.id = relationships.follower_id WHERE relationships.followed_id = " + current_user[:id].to_s + ") Y ON X.id = Y.id"
    @users = User.find_by_sql(friendsQuery)
    
    #binding.pry

    #自分が作成したタスク
    @tasks = Task.where.not(id: SubmitRequest.select(:task_id)).where(user_id: current_user.id, done: false)
    #binding pry
    #リクエスト新規作成用
    #@submit_request = current_user.submit_requests.build(status: 1)
    @submit_request = SubmitRequest.new(user_id: current_user[:id], status: 1)
    @user = @submit_request.user
  end

  def create
    #@comment = current_user.comments.build(comment_params)
    #@submit_request = SubmitRequest.new(submit_request_params)
     @submit_request = current_user.submit_requests.build(submit_request_params)
    #@task = Task.find(submit_request_params[:task_id])
    #binding.pry
   @notification = @submit_request.notifications.build(recipient_id: @submit_request.charge_id, sender_id: current_user.id, read: false)
   respond_to do |format|
      if @submit_request.save
        #保存できたら、依頼対象のタスク担当者を依頼先のユーザーに更新する
        @submit_request.task.update(status: 1, charge_id: submit_request_params[:charge_id])
        
        format.html { redirect_to @submit_request, notice: '依頼しました' }
        format.json { render :show, status: :created, location: @submit_request }
      else
        format.html { render :new }
        format.json { render json: @submit_request.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
  end

  def edit
    #つながっているユーザー
    friendsQuery = "select * FROM (SELECT users.* FROM users INNER JOIN relationships ON users.id = relationships.followed_id WHERE relationships.follower_id = " + current_user[:id].to_s + ") X INNER JOIN (SELECT users.* FROM users INNER JOIN relationships ON users.id = relationships.follower_id WHERE relationships.followed_id = " + current_user[:id].to_s + ") Y ON X.id = Y.id"
    @users = User.find_by_sql(friendsQuery)
    
    #@test = @submit_request
    #binding.pry
    
    #taskのidがSubmitRequestのtask_idでなく、かつ自分が作成した(user_idがcurrent_user.id) 未完成(doneがfalse)のタスク
    #@tasks = Task.where.not(id: SubmitRequest.select(:task_id)).where(user_id: current_user.id, done: false)
    
    #選択されたタスク
    @tasks = Task.where.not(id: SubmitRequest.select(:task_id)).where(user_id: current_user.id, done: false)
  end

  def update
     respond_to do |format|
      if @submit_request.update(submit_request_params)
        
        #依頼管理にひもずくタスクの担当者も更新される
        @submit_request.task.update(charge_id: submit_request_params[:charge_id])
        format.html { redirect_to @submit_request, notice: '更新しました' }
        format.json { render :show, status: :ok, location: @submit_request }
      else
        format.html { render :edit }
        format.json { render json: @submit_request.errors, status: :unprocessable_entity }
      end
    end
    
  end

  def destroy
  end

  def approve
    #@submit_request = SubmitRequest.find(params[:submit_request_id])
    #承認進み
    @submit_request02.update(status: 2)
    #依頼にひもずくタスクのステータスを承認にする
    #依頼管理にひもずくタスクの担当者も更新される
    @submit_request02.task.update(status: 2, charge_id: current_user.id)

    #binding.pry
    #現在依頼した本人が担当者になっている一覧を表示
    @Submit_Requests = SubmitRequest.where(charge_id: current_user.id).order("updated_at DESC")
    
    respond_to do |format|
    format.html { redirect_to  inbox_user_submit_requests_path(current_user.id) , notice: '承認しました' }
    format.js
      
      #format.html
     end
    
  end

  def unapprove
    #承認を却下
    @submit_request02.update(status: 9)
    #binding.pry
    #依頼にひもずくタスクの承認を却下し担当者を依頼主にもどす
    @submit_request02.task.update(status: 9, charge_id: @submit_request02.user_id)

    #現在依頼した本人が担当者になっている一覧を表示
    @submit_requests = SubmitRequest.where(charge_id: current_user.id).order("updated_at DESC")
    
    respond_to do |format|
     format.html { redirect_to inbox_user_submit_requests_path(current_user.id) , notice: '却下しました' }
     format.js
     #format.html
    end
  end

  def reject
    #承認取り消し
    @submit_request02.update(status: 8)
    #依頼者自らが取り消す。　タスクは取り消している本人にもどす
    @submit_request02.task.update(status: 8, charge_id: current_user.id)
    @submit_request02.destroy
    #自分が依頼しているもの一覧の表示
    @submit_requests = SubmitRequest.where(user_id: current_user.id).order("updated_at DESC")
    
    respond_to do |format|
     format.html { redirect_to user_submit_requests_path(current_user.id) , notice: '取り消しました' }
     format.js
    end
  end

  def inbox
    #依頼されているもの = 担当者が自分である　一覧表示
    #@Submit_Requests = SubmitRequest.where(charge_id: current_user.id).order("updated_at DESC")
    @Submit_Requests = SubmitRequest.where.not(status: 8).where(charge_id: current_user.id).order("updated_at DESC")
    
  end
  
  private
  
  def submit_request_params
    params.require(:submit_request).permit(:task_id, :user_id, :charge_id, :status, :message)
  end
  
   def set_submit_request
    @submit_request = SubmitRequest.find(params[:id])
  end
  
   def set_submit_request02
    @submit_request02 = SubmitRequest.find(params[:submit_requests_id])
   end
  
    def sending_pusher02
      Notification.sending_pusher(@notification.recipient_id)
    end
  
end

app/helpers/submit_requests_helper.rb
module SubmitRequestsHelper
end

app/views/submit_requests/_form.html.erb
<%= form_for([@user, @submit_request]) do |f| %>


 <div class="form-group"><%= f.collection_select :task_id, @tasks, :id, :title %></div>
 
 <div class="form-group"><%= f.collection_select :charge_id, @users, :id, :name %></div>
 
 <div class="form-group"><%= f.text_area  :message, placeholder: "依頼メッセージ", size: "50*100" %></div>
 <div class="form-group"><%= f.hidden_field :user_id%></div>
 <div class="form-group"><%= f.hidden_field :status %></div>
 <div><%= f.submit "依頼する", class: "btn btn-large btn-primary" %></div>
<% end %>

<%= link_to '依頼一覧', user_submit_requests_path %>

app/views/submit_requests/_submit_requests_list.html.erb
<% if submit_requests.present? %>
 <h4>自分が依頼したタスクは<%= submit_requests.count %>件です</h4>

  <table class="table table-bordered">
    <th>ステータス</th>
　　<th>タスク・タイトル</th>
　　<th>依頼者</th>
　　<th>担当者</th>
　　<th>依頼日</th>
　　<th>タスク・ステータス</th>
　　<tbody>
    <% submit_requests.each do |sr| %>
      <tr>
       <!--ステータス -->
       <% if sr.status == 1 %>
        <td>未承認</td>
       <% elsif sr.status == 2 %>
         <td>了承されました。</td>
       <% elsif sr.status == 8 %>
        <td>依頼を取り消しました。</td>
       <% elsif sr.status == 9 %>
         <td>却下されました。</td> 
       <% end %>
       
       <!--タスク・タイトル -->
       <td><%= link_to sr.task.title , task_path(sr.task) %></td>
       
       <!--タスク登録者 -->
       <td><%= sr.user.name %></td>
       
       <!--担当者 -->      
       <% if sr.charger.id == current_user.id %>
       <td>自分</td>
       <% else %>
       <td><%= sr.charger.name %></td>
       <% end %>
       
       <!--依頼日 -->
       <td><%= sr.created_at.strftime("%Y年 %m月 %d日")%></td>
 
       <!--タスク・ステータ日 -->
        <% if sr.task.done == true %>
       <td>完了</td>
       <% else %>
       <td>未完了</td>
       <% end %>
       
       <td><%= link_to '詳細',submit_request_path(sr)%></td>
       <% if  sr.status == 2 or sr.status == 8 %>
       <td>&emsp;&emsp;</td>
       <% else %>
       <td><%= link_to '編集',edit_submit_request_path(sr)%></td>
       <% end %>
       
       <!--ステータス -->
       <% if  sr.status == 1 %>
       <td> <%= link_to "依頼の取り消し", submit_request_reject_path(sr) %></td>
       <% else %>
       <td>&emsp;&emsp;</td>
       <% end %>
      </tr>
    <% end %>
　　</tbody>
   </table>
 <%end %>
 
 <%= link_to '新規依頼',new_user_submit_request_path, class: "btn btn-large btn-primary"%>
 <%= link_to '依頼されている一覧',inbox_user_submit_requests_path , class: "btn btn-large btn-primary"%>

app/views/submit_requests/approve.js.erb
$("#inbox_list_<%= current_user.id %>").html("<%= escape_javascript(render partial: 'submit_requests_list', locals: {submit_requests: @submit_requests} ) %>");

app/views/submit_requests/create.html.erb
<h1>SubmitRequests#create</h1>
<p>Find me in app/views/submit_requests/create.html.erb</p>

app/views/submit_requests/edit.html.erb
<h4>依頼管理編集</h4>

<%= render'edit_form' %>

<%= link_to '詳細' , submit_request_path(@submit_request) %>
<%= link_to '戻る' , user_submit_requests_path(@submit_request) %>

app/views/submit_requests/inbox.html.erb
<div id="inbox_list_<%= current_user.id %>" >
<%= render partial: 'submit_requests_list_inbox', locals: { submit_requests: @Submit_Requests} %>
</div>

app/views/submit_requests/inbox.js.erb
$("#inbox_list_<%= current_user.id %>").html("<%= escape_javascript(render partial: 'submit_requests_list', locals: {submit_requests: @submit_requests} ) %>");

app/views/submit_requests/index.js.erb
$("#inbox_list_<%= current_user.id %>").html("<%= escape_javascript(render partial: 'submit_requests_list', locals: {submit_requests: @submit_requests} ) %>");

app/views/submit_requests/new.html.erb
<div>
 <h1>依頼する内容</h1>
    <div>
    <% if @tasks.present? %>
         <%= render'form' %>
    <% else %>
         依頼できるものがありません
    <% end %>
    </div>
 </div>
 
 <%= link_to '戻る',user_submit_requests_path(@submit_request.user_id) %>

app/views/submit_requests/reject.html.erb
<h1>SubmitRequests#reject</h1>
<p>Find me in app/views/submit_requests/reject.html.erb</p>

app/views/submit_requests/reject.js.erb
$("#submit_requests_<%= current_user.id %>").html("<%= escape_javascript(render partial: 'submit_requests_list', locals: {submit_requests: @submit_requests} ) %>");

app/views/submit_requests/show.html.erb
<div class="panel panel-default">
    

    <div class="panel-heading">依頼者:</div>
    <div class="panel-body"><%= @submit_request.user.name if @submit_request.user.present? %></div>

<div class="panel-heading">タスク名：</div>
<div class="panel-body"> <%= @submit_request.task.title %></div>


<div class="panel-heading">担当者：</div>
<div class="panel-body"> <%= @submit_request.charger.name if @submit_request.user.present? %></div>

<div class="panel-heading">ステータス：</div>
<div class="panel-body">
    <%= if @submit_request.status == 0 then "未依頼"
    elsif @submit_request.status == 1 then "依頼中" 
    elsif @submit_request.status == 2 then "承認済み" 
    elsif @submit_request.status == 8 then "取り消し済み" 
    elsif @submit_request.status == 9 then "却下済み" 
    end %></div>


<div class="panel-heading">メッセージ:</div>
<div class="panel-body"><%= @submit_request.message %></div>
</div>
<%= link_to '編集' , edit_submit_request_path(@submit_request) %>
<%= link_to '戻る' , user_submit_requests_path(@submit_request) %>

app/views/submit_requests/unapprove.html.erb
<h4>SubmitRequests#unapprove</h4>
<div>Find me in app/views/submit_requests/unapprove.html.erb</div>

app/views/submit_requests/unapprove.js.erb
$("#inbox_list_<%= current_user.id %>").html("<%= escape_javascript(render partial: 'submit_requests_list', locals: {submit_requests: @submit_requests} ) %>");