config/routes.rb
Rails.application.routes.draw do
 
  #get 'notifications/index'

 resources :projecttasks
  
  resources :customers
  
  resources :projects do
   resources :projecttasks
   resources :memberships
   member do
    get :membering;
    get :member_list;
   end
  end
  
  namespace :taskline do
    resources :task_comments
  end
  resources :tasks

resources :qacomments
  resources :qas do
   resources :qacomments
  end
  
  resources :comments
  get 'users/index'
  get 'users/show'

  devise_for :users, controllers: { 
   sessions: "users/sessions", 
   registrations: "users/registrations", 
   passwords: "users/passwords",
   omniauth_callbacks: "users/omniauth_callbacks" 
  }
  
  resources :users, only:[:index, :show, :update] do
   resources :tasks
   resources :notifications, only: [:index]
   member do
    get :following, :followers;    
   end
   
   resources :submit_requests , shallow: true do
    get 'approve'
    get 'unapprove'
    get 'reject'
     collection do
      get 'inbox'
     end
    end
   end
  
  namespace :taskline do
   resources :tasks do
   resources :task_comment
   post "ungoodjob"
   post "goodjob"
  end
 end
 

  resources :relationships, only:[:create, :destroy]
  
  root to: "top#index"
  get 'contact/index'
  get 'contact/new'
  post 'contact/confirm'
  post 'contact/thanks'
  
  resources :blogs do
    resources :comments
  end
  
  resources :conversations do
   resources :messages
  end
  

  

end

app/models/project.rb
class Project < ActiveRecord::Base

  belongs_to :user
  belongs_to :customer
  has_many :projecttasks, dependent: :destroy
  has_many :memberships, dependent: :destroy
  
  validates :title, presence: { message: "プロジェクト名を入力してください" }
  validates  :content, presence: { message: "内容を入力してください" }
  validates :deadline, timeliness: { on_or_after: :now }

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
    

  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
    @customers = Customer.all
    @memberships = Membership.all
    #binding pry
  end

  # GET /projects/1/edit
  def edit
    @customers = Customer.all
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: '新規プロジェクトを登録しました。' }
        format.json { render :show, status: :created, location: @project }
      else
         @customers = Customer.all
        format.html { render :new}
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'プロジェクトを更新しました。' }
        format.json { render :show, status: :ok, location: @project }
      else
         @customers = Customer.all
        format.html { render :edit }
        #format.js { render :index, notice: 'プロジェクトを削除しました。' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: '新規プロジェクトを削除しました。' }
      format.json { head :no_content }
    end
  end


  def  membering
    @users = User.page(params[:page])
    session[:@pj_num]= params[:id]
    @pj_num = session[:@pj_num]
    
    #binding pry
    #参加しているか確認する
    @member_list = Membership.where(project_id: params[:id])
    #binding pry
  end
  
  def  member_list
    @project_master =Project.find(params[:id])
    
    #参加しているか確認する
    @member_list = Membership.where(project_id: params[:id])

  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:user_id, :title, :content, :deadline, :customer_id, :done, :status)
    end
    
     # Never trust parameters from the scary internet, only allow the white list through.
    def membership_params
      params.require(:membership).permit(:user_id, :project_id)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_add_form.html.erb
<%=form_for(user,url:project_memberships_path(user),method: :post , remote:true) do|f| %>
<div>
<%= hidden_field_tag 'membership[user_id]',user.id %>
<%= hidden_field_tag 'membership[project_id]', session[:@pj_num] %>
</div>
<%=f.submit"メンバーに追加" , class:"btn btn-large btn-primary"%>
<% end %>

app/views/projects/_dele_form.html.erb
<%=form_for(user,url:project_membership_path(session[:@pj_num], user),method: :delete, remote:true) do|f| %>
<div>
<%= hidden_field_tag 'membership[user_id]',user.id %>
<%= hidden_field_tag 'membership[project_id]', @pj_num %>
</div>
<%=f.submit"メンバーから削除" , class:"btn btn-warning"%>

<% end %>

app/views/projects/_form.html.erb
<div class="list-group" >
<%= form_for(@project) do |f| %>

  <% if @project.errors.any? %>

      <h4><%= @project.errors.count %> 個のエラー</h4>
      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
  <% end %>
  
  
  

  <div class="field">
    <%= hidden_field_tag 'project[user_id]', current_user.id %>
  </div>
  
  <div class="list-group-item">
    <%= f.label :プロジェクト名 %><br>
    <%= f.text_field :title %>
  </div>
  <div class="list-group-item">
    <%= f.label :内容 %><br>
    <%= f.text_area :content %>
  </div>
  <div class="list-group-item">
    <%= f.label :締め切り %><br>
        <%= f.date_select(
         :deadline,
          start_year: Time.now.year,
          end_year:   Time.now.year + 18,
          default:   Time.now) %>
  </div>
  <div class="list-group-item">
    <%= f.label :顧客 %><br>
    <%= f.select :customer_id, @customers.map{|t| [t.customer_name, t.id]} %>
  </div>
  <div class="list-group-item">
    <%= f.label :完了 %><br>
    <%= f.check_box :done %>
  </div>
  <div class="list-group-item">
    <%= f.label :ステータス %><br>
    <%= f.select:status,[["未着手","0"],["対応中","1"]] %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/projects/_member.html.erb
<div class="boxb">

<% @member_list.each do |member| %>
 <% unless current_user?(member) %>
<div class="list-group-item"><%= member.user.name %> </div>
<% end %>
<% end %>

</div>

app/views/projects/_user.html.erb
<% @users.each do |user| %>

 <div class="boxb">
 <div><%=link_to user.name , user %>を </div>

  <div id="add_del_form_<%= user.id %>">
    <% if  member_project_num?( @pj_num , user.id ) %>
        <%= render partial:'dele_form',locals:{user: user} %>
     <% else %>   
        <%= render partial:'add_form',locals:{user: user} %>
    <% end %>
  </div> 
  
 </div>

<% end %>

app/views/projects/edit.html.erb
<h4>プロジェクトの編集</h4>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h2>マイプロジェクト</h2>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>プロジェクト名</th>
      <th>作成者</th>
      <th>概要</th>
      <th>締め切り</th>
      <th>顧客</th>
      <th>ステータス</th>
      <th colspan="3"></th>
      <th colspan="2">メンバー管理</th>
      <th>タスク管理</th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.title %></td>
        <td><%= project.user.name %></td>
        <td><%= project.content %></td>
        <td><%= project.deadline.strftime("%Y年%m月%d日") %></td>
        <td><%= project.customer.customer_name %></td>
        <td><%= if project.status ==1 then "対応中" elsif project.status ==0 then "未着手" end %></td>

          <% if pj_member?(project.id) || current_user.id == project.user.id %>
          
         <td><%= link_to 'プロジェクト詳細', project %> </td>
        <% if current_user.id == project.user.id %>
        <td><%= link_to '編集', edit_project_path(project) %></td>
        <td><%= link_to '削除', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% else %>
        <td colspan="2"></td>
         <% end %>
        
        <td><%= link_to 'メンバ一選択', membering_project_path(project) %></td>
        <td><%= link_to 'メンバー一覧', member_list_project_path(project) %></td>
        
        <td><%= link_to 'タスク一覧', project_projecttasks_path(project) %></td></td>
        
          <% else %>
         <td colspan="6"></td>
         <% end %>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<button type="button" class="btn btn-default">
<%= link_to '新規プロジェクト作成', new_project_path %>
</button>

<button type="button" class="btn btn-default">
<%= link_to '顧客管理', customers_path %>
</button>

app/views/projects/member_list.html.erb
<% provide(:title, 'メンバー一覧') %>
<h4>プロジェクト作成者</h4>
<%=@project_master.user.name %>
<h4>メンバー一覧</h4>
<div class="list-group">
<div>
  <%= render 'member', locals: { member: @member_list }%>
</div>

</div>

app/views/projects/membering.html.erb
<% provide(:title, '全てのユーザー') %>
<h3>メンバー管理</h3>

<div class="row2">
<ul class="users">
  <%= render 'user', locals: { user: @users }%>
</ul>
</div>

<div class="clear">
<%= paginate @users %>
</div>

app/views/projects/new.html.erb
<h4>新規プロジェクト登録</h4>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<h4>プロジェクト詳細</h4>
<div class="list-group">
  
<div  class="list-group-item">
  <strong>プロジェクト名:</strong>
  <%= @project.title %>
</div>

<div  class="list-group-item">
  <strong>作成者:</strong>
  <%= @project.user.name %>
</div>

<div class="list-group-item">
  <strong>内容:</strong>
  <%= @project.content %>
</div>

<div  class="list-group-item">
  <strong>締め切り:</strong>
  <%= @project.deadline.strftime("%Y年%m月%d日") %>
</div>

<div  class="list-group-item">
  <strong>顧客:</strong>
  <%= @project.customer.customer_name %>
</div>

<div  class="list-group-item">
  <strong>完了:</strong>
  <%= if @project.done? then "完了" else "未完了" end%>
</div>

<div class="list-group-item">
  <strong>ステータス:</strong>
  <%= if @project.status ==1 then "対応中" elsif @project.status ==0 then "未着手" end %>
</div>

</div>
<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>