config/routes.rb
Rails.application.routes.draw do
 
  #get 'notifications/index'

 resources :projecttasks
  
  resources :customers
  
  resources :projects do
   resources :projecttasks
   resources :memberships
   member do
    get :membering;
    get :member_list;
   end
  end
  
  namespace :taskline do
    resources :task_comments
  end
  resources :tasks

resources :qacomments
  resources :qas do
   resources :qacomments
  end
  
  resources :comments
  get 'users/index'
  get 'users/show'

  devise_for :users, controllers: { 
   sessions: "users/sessions", 
   registrations: "users/registrations", 
   passwords: "users/passwords",
   omniauth_callbacks: "users/omniauth_callbacks" 
  }
  
  resources :users, only:[:index, :show, :update] do
   resources :tasks
   resources :notifications, only: [:index]
   member do
    get :following, :followers;    
   end
   
   resources :submit_requests , shallow: true do
    get 'approve'
    get 'unapprove'
    get 'reject'
     collection do
      get 'inbox'
     end
    end
   end
  
  namespace :taskline do
   resources :tasks do
   resources :task_comment
   post "ungoodjob"
   post "goodjob"
  end
 end
 

  resources :relationships, only:[:create, :destroy]
  
  root to: "top#index"
  get 'contact/index'
  get 'contact/new'
  post 'contact/confirm'
  post 'contact/thanks'
  
  resources :blogs do
    resources :comments
  end
  
  resources :conversations do
   resources :messages
  end
  

  

end

app/models/projecttask.rb
class Projecttask < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
  # validates :project_id , presence: { message: "aaaaaaa" }
  validates :projecttask_title, presence: { message: "タスク名を入力してください" }
  validates :projecttask_content, presence: { message: "内容を入力してください" }
  validates :projecttask_deadline, timeliness: { on_or_after: :now }
  
end

app/controllers/projecttasks_controller.rb
class ProjecttasksController < ApplicationController
  before_action :set_projecttask, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /projecttasks
  # GET /projecttasks.json
  def index
    @projecttasks = Projecttask.all
    #binding.pry
    @project = Project.find(params[:project_id])
    
    @users = User.all
    
    @pj_num = params[:project_id]#
    @member_list = Membership.where(project_id: @pj_num)
    #binding.pry
    

  end

  # GET /projecttasks/1
  # GET /projecttasks/1.json
  def show
    @users = User.all
  end

  # GET /projecttasks/new
  def new
    @projecttask = Projecttask.new

    #Parameters: {"project_id"=>"6"}
    @pj_num = params[:project_id]
    session[:@pj_num] = @pj_num
    #binding pry
 
    @member_list = Membership.where(project_id: session[:@pj_num])
    
    @members_for_options = Hash.new
    @member_list.each do |member|
      @members_for_options.store(member.user.name, member.user.id)
    end
    
    #binding pry
  end

  # GET /projecttasks/1/edit
  def edit
    #@pj_num = params[:project_id]
    session[:@pj_num3] = params[:project_id]
   
    @member_list = Membership.where(project_id: session[:@pj_num3] )
    @members_for_options = Hash.new
    @member_list.each do |member|
      @members_for_options.store(member.user.name, member.user.id)
    end
  end

  # POST /projecttasks
  # POST /projecttasks.json
  def create
   # @projecttask = Projecttask.new(projecttask_params)
    @projecttask= current_user.projecttasks.build(projecttask_params)
    #binding pry
    
    respond_to do |format|
      if @projecttask.save
        
        #@pj_num =pj_params
         #binding pry
      
        @pj_num2 = session[:@pj_num]
        #binding pry
        format.html {redirect_to project_projecttasks_url(@pj_num2) , notice: '新規タスクを作成しました' }
        
        format.json { render :show, status: :created, location: project_projecttasks_path }
      else
        #@pj_num = params[:pj_num]
        #@pj_num2 = @pj_num[:project_id2]
        @pj_num = session[:@pj_num] 
       #binding pry
       format.html{ render :new }
       # format.html { render "projects/#{@pj_num2}/projecttasks/new" }
        
        
       # format.json { render json: @projecttask.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projecttasks/1
  # PATCH/PUT /projecttasks/1.json
  def update
    respond_to do |format|

      if @projecttask.update(projecttask_params)
        
        @pj_num = session[:@pj_num3] 
        #binding.pry
        
        #@pj_num2 = @pj_num[:project_id2]
        
        format.html { redirect_to  project_projecttasks_url(@pj_num) , notice: '更新しました' }
        format.json { render :show, status: :ok, location: @projecttask }
      else
        format.html { render :edit }
        format.json { render json: @projecttask.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projecttasks/1
  # DELETE /projecttasks/1.json
  def destroy
    @projecttask.destroy
    respond_to do |format|
      format.html { redirect_to project_projecttasks_url, notice: 'タスクを削除しました' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_projecttask
      @projecttask = Projecttask.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def projecttask_params
      params.require(:projecttask).permit(:user_id, :project_id, :projecttask_title, :projecttask_content, :projecttask_deadline, :projecttask_charge_id, :projecttask_done, :projecttask_status)
    end
    
    
end

app/helpers/projecttasks_helper.rb
module ProjecttasksHelper
end

app/views/projecttasks/_form.html.erb
<div class="list-group" >
<%= form_for(@projecttask) do |f| %>
  <% if @projecttask.errors.any? %>

      <h4><%= @projecttask.errors.count %> 個のエラー</h4>
      <ul >
      <% @projecttask.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>

  <% end %>

  <div class="list-group-item">
    <%= f.label :タスク名 %><br>
    <%= f.text_field :projecttask_title %>
 
  </div>
  
   <div class="list-group-item">
    <%= f.label :プロジェクトID %><br>
    <input type="hidden" name="projecttask[project_id]" id="projecttask_project_id" value="<%=  session[:@pj_num]  %>" />
 
  </div>
  
  <div class="list-group-item">
    <%= f.label :内容 %><br>
    <%= f.text_area :projecttask_content %>
  </div>
  <div class="list-group-item">
    <%= f.label :期日 %><br>
    <%= f.date_select(
         :projecttask_deadline,
          start_year: Time.now.year,
          end_year:   Time.now.year + 18,
          default:   Time.now) %>
    
  </div>
  <div class="list-group-item">
    <%= f.label :担当者 %><br>

    <% if @members_for_options.blank? %>
    <select name="projecttask[projecttask_charge_id]" id="projecttask_projecttask_charge_id">
      <option value="0">admin</option>
      </select>
      <% else %>
      <%= select_tag "projecttask[projecttask_charge_id]", options_for_select(@members_for_options) %>
    <% end %>

  </div>
  <div class="list-group-item">
    <%= f.label :完了 %><br>
    <%= f.check_box :projecttask_done %>
  </div>
  <div class="list-group-item">
    <%= f.label :ステータス%><br>
    <%= f.select:projecttask_status,[["未着手","0"],["対応中","1"]] %>
  </div>



  <div class="field">
    <%= hidden_field_tag ' projecttask[user_id]', current_user.id %>

    </div>
      <div class="actions">
    <%= f.submit %>
  </div>
  </div>
  <% end %>
   <div class="list-group-item">
    <% #f.text_field :project_id %>
    
    
     <%= hidden_field_tag 'pj_num[project_id2]', session[:@pj_num] %>

  </div>

app/views/projecttasks/_form1.html.erb
<div class="list-group" >
<%= form_for(@projecttask) do |f| %>
  <% if @projecttask.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@projecttask.errors.count, "error") %> prohibited this projecttask from being saved:</h2>

      <ul>
      <% @projecttask.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


    <%= hidden_field_tag ' projecttask[user_id]', current_user.id %>

    
    <% #hidden_field_tag 'pj_num[project_id2]', @pj_num %>
  <div class="field">
     <%= hidden_field_tag ' projecttask[project_id]', @pj_num %>
  </div>

  <div class="list-group-item">
    <%= f.label :タスク名 %><br>
    <%= f.text_field :projecttask_title %>
  </div>
  <div class="list-group-item">
    <%= f.label :内容 %><br>
    <%= f.text_area :projecttask_content %>
  </div>
  <div class="list-group-item">
    <%= f.label :締め切り %><br>
    <%= f.datetime_select :projecttask_deadline %>
  </div>
  <div class="list-group-item">
    <%= f.label :担当者 %><br>
    <%= select_tag "projecttask[projecttask_charge_id]", options_for_select(@members_for_options) %>

  </div>
  <div class="list-group-item">
    <%= f.label :完了 %><br>
    <%= f.check_box :projecttask_done %>
  </div>
  <div class="field  list-group-item">
    <%= f.label :ステータス%><br>
    <%= f.select:projecttask_status,[["未着手","0"],["対応中","1"]] %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/projecttasks/create.js.erb
$('.area').html('<%= escape_javascript(render partial:'projecttasks/form',locals: @projecttask ) %>');

app/views/projecttasks/edit.html.erb
<h4>タスクの編集</h4>

<%= render 'form' %>


<a href="/projects/<%= session[:@pj_num3] %>/projecttasks">Back</a> 

app/views/projecttasks/index.html.erb
<h4><%= @project.title %>のタスク一覧</h4>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>タスク名</th>
      <th>タスク作成者</th>
      <th>タスク内容</th>
      <th>締め切り</th>
      <th>担当者</th>
      <th>完了</th>
      <th>ステータス</th>
      <th colspan="3"></th>
    </tr>
  </thead>


  <tbody>


  
    <% @projecttasks.each do |projecttask| %>
    <% num = @pj_num.to_i %>
    <% if num == projecttask.project_id %>

      <tr>
       <td><%= projecttask.projecttask_title %></td>
        <td><%= projecttask.user.name %></td>
        <td><%= projecttask.projecttask_content %></td>
        <td><%= projecttask.projecttask_deadline.strftime("%Y年%m月%d日") %></td>
        
       <% if projecttask.projecttask_charge_id == 0  %>
       <td>admin</td>
       <% else %>
        <% @users.each do |user| %>
           <% if user.id == projecttask.projecttask_charge_id %>
               <td><%= user.name %></td>
           <% end %>
        <% end %>
      <% end %>

        
        <td><%= if projecttask.projecttask_done? then "完了" else "未完了" end%></td>
        

         <td><%= if projecttask.projecttask_status ==1 then "対応中" elsif projecttask.projecttask_status ==0 then "未着手" end %></td>
        <td><%= link_to 'タスク詳細', project_projecttask_path(@pj_num,projecttask) %></td>
        
         <% if current_user.id == projecttask.user.id %>

        <td><%= link_to '編集', edit_project_projecttask_path(@pj_num,projecttask) %></td>
        <td><%= link_to '削除', project_projecttask_path(@pj_num,projecttask), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% else %>
        <td colspan="2"></td>
        <% end %>
        
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>
<button type="button" class="btn btn-default">
<%= link_to '新規タスク', new_project_projecttask_path %>
</button>

app/views/projecttasks/new.html.erb
<h4>新規タスク登録</h4>
<div class="area">
<%= render 'form' %>
</div>

<%= link_to 'Back', projecttasks_path %>

app/views/projecttasks/show.html.erb
<h4>タスク詳細</h4>
<div class="list-group">

<div class="list-group-item">
  <strong>担当者:</strong>
  
    <% @users.each do |user| %>
        <% if user.id == @projecttask.projecttask_charge_id %>
        <td><%= user.name %></td>
        <% end %>
     <% end %>
</div>


<div class="list-group-item">
  <strong>タスク名:</strong>
  <%= @projecttask.projecttask_title %>
</div>

<div class="list-group-item">
  <strong>タスク内容:</strong>
  <%= @projecttask.projecttask_content %>
</div>

<div class="list-group-item">
  <strong>締切日:</strong>
 <%= @projecttask.projecttask_deadline.strftime("%Y年%m月%d日") %>
</div>



<div class="list-group-item">
  <strong>完了:</strong>
　<%= if @projecttask.projecttask_done? then "完了" else "未完了" end%>
</div>

<div class="list-group-item">
  <strong>ステータス:</strong>
　<%= if @projecttask.projecttask_status ==1 then "対応中" elsif @projecttask.projecttask_status ==0 then "未着手" end %>
</div>

</div>

<%= link_to 'Edit', edit_project_projecttask_path %> |
<%= link_to 'Back', project_projecttasks_path %>